In [1]:
import torch

c:\Users\Efran\anaconda3\envs\tpatches_env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [26]:
x1 = torch.randn([2, 4096, 3])
x2 = torch.randn([2, 4096, 3])

In [36]:
x1.reshape(x1.flatten().shape, 1).shape

torch.Size([24576])

In [51]:
dist = torch.norm(x1.flatten().view(1, -1) - x2.flatten().view(1, -1), dim=1, p=None)
dist

tensor([220.5818])

In [73]:
dist = torch.norm(x1.flatten().view(1, -1) - x2.flatten().view(1, -1), dim=1, p=None)
knn = dist.topk(3, largest=False)

RuntimeError: selected index k out of range

In [44]:
knn.values

tensor([4.2200e-05, 1.1060e-04, 1.5724e-04])

In [45]:
knn.indices

tensor([18664, 17555, 21798])

### temp

In [68]:
from sklearn.neighbors import KDTree
k = 16

In [69]:
x1 = torch.randn([2, 4096, 3])
x2 = torch.randn([2, 4096, 3])

In [70]:
tree = KDTree(x2.reshape(-1, 1))
distances, idxs = tree.query(x1.reshape(-1, 1), k)
distances, idxs = torch.tensor(distances).cuda(), torch.tensor(idxs).cuda()

In [72]:
distances.shape

torch.Size([24576, 16])